config/routes.rb
Resocialbuilder::Application.routes.draw do
  
  

  constraints(:subdomain => 'soulmate') do
    mount Soulmate::Server, :at => '/'
  end
  
  constraints(:subdomain => 'dev') do
    mount Resque::Server, :at => '/resque'
    scope :module => "dev" do
      get '/sprites/:id' => 'dev#sprites'
      get '/sprites' => 'dev#sprites'
      get '/schema' => 'dev#schema'
      root to: "dev#index"
    end
  end
  
  match '/dashboard', to: 'dashboard::dashboard#index', as: 'dashboard'
  match '/login', to: 'accounts#login'
  match '/logout', to: 'sessions#logout'

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure', to: 'home::register#new', as: 'register'
  
  
  match 'listings/nnrmls', to: 'listings#nnrmls', as: 'nnrmls'
  match 'listings/stgeorge', to: 'listings#stgeorge', as: 'stgeorge'
  match 'listings/mls', to: 'listings#mls', as: 'mls'
  
  mount Ckeditor::Engine => "/ckeditor"
  
  namespace :dashboard do
    
    
    
    match '/', to: 'dashboard#index', as: 'dashboard'
    match '/mls', to: 'dashboard#mls', as: 'mls'
    match '/menu', to: 'dashboard#menu', as: 'menu'
    match '/support', to: 'dashboard#support', as: 'support'
    match '/settings', to: 'dashboard#settings', as: 'settings'
    post '/savesort' => 'pages#savesort'
    
    
    
    resources :blogs do
      resources :comments
    end
    
    get 'blogs/:id/manage_comments', to: 'blogs#manage_comments', as: 'manage_comments'
    
    resources :accounts
    resources :comments
    resources :pages
    resources :links
    resources :widgets
    resources :realtors
    resources :listings
    resources :transactions
    resources :cards
    resources :facebook_posts

    
  end
  
  
  
  constraints(Subdomain) do
    
    namespace :api do
      namespace :v1, :defaults => { :format => 'json' } do
        resources :blogs
        resources :pages
        resources :accounts
        resources :listings
      end
    end
  
    post '/emails', to: 'profile::profile#emails', as: 'emails', :via => :post


    get '/listings', to: 'profile::profile#listings', as: 'listings', :via => :get
    match '/listing/:mls_list_id', to: 'profile::profile#listing', as: 'listing', :via => :get
    
    
    
    get '/blogs', to: 'profile::profile#blogs', as: 'blogs', :via => :get
    match '/blog/:id', to: 'profile::profile#blog', as: 'blog', :via => :get
    
    match '/search', to: 'profile::profile#search', as: 'searches', :via => :get
    resources :search

    match '/:id', to: 'profile::profile#page', as: 'page', :via => :get

    
    root to: 'profile::profile#index'
  end
  

  resources :accounts
  resources :realtors
  resources :listings
  
  root :to => 'home::home#index'
  
end

app/controllers/realtors_controller.rb
class RealtorsController < ApplicationController
  # GET /realtors
  # GET /realtors.json
  def index
    @realtors = Realtor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @realtors }
    end
  end

  # GET /realtors/1
  # GET /realtors/1.json
  def show
    @realtor = Realtor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @realtor }
    end
  end

  # GET /realtors/new
  # GET /realtors/new.json
  def new
    @realtor = Realtor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @realtor }
    end
  end

  # GET /realtors/1/edit
  def edit
    @realtor = Realtor.find(params[:id])
  end

  # POST /realtors
  # POST /realtors.json
  def create
    @realtor = Realtor.new(params[:realtor])

    respond_to do |format|
      if @realtor.save
        format.html { redirect_to @realtor, notice: 'Realtor was successfully created.' }
        format.json { render json: @realtor, status: :created, location: @realtor }
      else
        format.html { render action: "new" }
        format.json { render json: @realtor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /realtors/1
  # PUT /realtors/1.json
  def update
    @realtor = Realtor.find(params[:id])

    respond_to do |format|
      if @realtor.update_attributes(params[:realtor])
        format.html { redirect_to @realtor, notice: 'Realtor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @realtor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /realtors/1
  # DELETE /realtors/1.json
  def destroy
    @realtor = Realtor.find(params[:id])
    @realtor.destroy

    respond_to do |format|
      format.html { redirect_to realtors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/realtors_helper.rb
module RealtorsHelper
end

app/views/realtors/_form.html.haml
= semantic_form_for @realtor do |f|
  = f.inputs do
    = f.input :avatar
    = image_tag @realtor.avatar_url(:thumb) if @realtor.avatar?
    = f.input :first_name
    = f.input :last_name
    = f.input :mls_agent_id
    = f.input :email
    = f.input :password
    = f.input :phone
    = f.input :time_zone

  = f.actions do
    = f.action :submit, :as => :input

app/views/realtors/edit.html.haml
%h1 Editing realtor

= render 'form'

= link_to 'Show', @realtor
\|
= link_to 'Back', realtors_path

app/views/realtors/index.html.haml
%h1 Listing realtors

%table
  %tr
    %th Realtor
    %th Mls agent
    %th Email
    %th Password
    %th Phone
    %th Time zone
    %th
    %th
    %th

  - @realtors.each do |realtor|
    %tr
      %td
        = image_tag realtor.avatar_url(:small) if realtor.avatar?
        = realtor.first_name
        = realtor.last_name
      %td= realtor.mls_agent_id
      %td= realtor.email
      %td= realtor.password
      %td= realtor.phone
      %td= realtor.time_zone
      %td= link_to 'Show', realtor
      %td= link_to 'Edit', edit_realtor_path(realtor)
      %td= link_to 'Destroy', realtor, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Realtor', new_realtor_path

app/views/realtors/new.html.haml
%h1 New realtor

= render 'form'

= link_to 'Back', realtors_path

app/views/realtors/show.html.haml
%p#notice= notice

= image_tag @realtor.avatar_url(:thumb) if @realtor.avatar?
%p
  %b Account:
  = @realtor.account_id
%p
  %b First name:
  = @realtor.first_name
%p
  %b Last name:
  = @realtor.last_name
%p
  %b Mls agent:
  = @realtor.mls_agent_id
%p
  %b Email:
  = @realtor.email
%p
  %b Password:
  = @realtor.password
%p
  %b Phone:
  = @realtor.phone
%p
  %b Time zone:
  = @realtor.time_zone

= link_to 'Edit', edit_realtor_path(@realtor)
\|
= link_to 'Back', realtors_path