config/routes.rb
Resocialbuilder::Application.routes.draw do
  
  

  constraints(:subdomain => 'soulmate') do
    mount Soulmate::Server, :at => '/'
  end
  
  constraints(:subdomain => 'dev') do
    mount Resque::Server, :at => '/resque'
    scope :module => "dev" do
      get '/sprites/:id' => 'dev#sprites'
      get '/sprites' => 'dev#sprites'
      get '/schema' => 'dev#schema'
      root to: "dev#index"
    end
  end
  
  match '/dashboard', to: 'dashboard::dashboard#index', as: 'dashboard'
  match '/login', to: 'accounts#login'
  match '/logout', to: 'sessions#logout'

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure', to: 'home::register#new', as: 'register'
  
  
  match 'listings/nnrmls', to: 'listings#nnrmls', as: 'nnrmls'
  match 'listings/stgeorge', to: 'listings#stgeorge', as: 'stgeorge'
  match 'listings/mls', to: 'listings#mls', as: 'mls'
  
  mount Ckeditor::Engine => "/ckeditor"
  
  namespace :dashboard do
    
    
    
    match '/', to: 'dashboard#index', as: 'dashboard'
    match '/mls', to: 'dashboard#mls', as: 'mls'
    match '/menu', to: 'dashboard#menu', as: 'menu'
    match '/support', to: 'dashboard#support', as: 'support'
    match '/settings', to: 'dashboard#settings', as: 'settings'
    post '/savesort' => 'pages#savesort'
    
    
    
    resources :blogs do
      resources :comments
    end
    
    get 'blogs/:id/manage_comments', to: 'blogs#manage_comments', as: 'manage_comments'
    
    resources :accounts
    resources :comments
    resources :pages
    resources :links
    resources :widgets
    resources :realtors
    resources :listings
    resources :transactions
    resources :cards
    resources :facebook_posts

    
  end
  
  
  
  constraints(Subdomain) do
    
    namespace :api do
      namespace :v1, :defaults => { :format => 'json' } do
        resources :blogs
        resources :pages
        resources :accounts
        resources :listings
      end
    end
  
    post '/emails', to: 'profile::profile#emails', as: 'emails', :via => :post


    get '/listings', to: 'profile::profile#listings', as: 'listings', :via => :get
    match '/listing/:mls_list_id', to: 'profile::profile#listing', as: 'listing', :via => :get
    
    
    
    get '/blogs', to: 'profile::profile#blogs', as: 'blogs', :via => :get
    match '/blog/:id', to: 'profile::profile#blog', as: 'blog', :via => :get
    
    match '/search', to: 'profile::profile#search', as: 'searches', :via => :get
    resources :search

    match '/:id', to: 'profile::profile#page', as: 'page', :via => :get

    
    root to: 'profile::profile#index'
  end
  

  resources :accounts
  resources :realtors
  resources :listings
  
  root :to => 'home::home#index'
  
end

app/controllers/dashboard/blogs_controller.rb
class Dashboard::BlogsController < Dashboard::DashboardController

  before_filter :setup_menu

  def setup_menu
    gon.menu_active_accordian = 0
    gon.menu_active_link = 'blogs'
  end

  def index
    @blogs = current_account.blogs.desc(:created_at)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end


  def show
    @blog = current_account.blogs.find_by_slug(params[:id])

    respond_to do |format|
      format.html { render "edit" }
      format.json { render json: @blog }
    end
  end
  
  def manage_comments
    @blog = current_account.blogs.find_by_slug(params[:id])
    
    @commentable = @blog
    @comments = @commentable.comments
    @comment = Comment.new
  

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  def new
    @blog = current_account.blogs.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end


  def edit
    @blog = current_account.blogs.find_by_slug(params[:id])
  end


  def create
    @blog = current_account.blogs.new(params[:blog])

    respond_to do |format|
      if @blog.save
        
        # Activity.create_indexes
        
        # current_account.publish_activity(:new_blog, :object => @blog)
        
        soul = Soulmate::Loader.new("blog #{current_account.id}")
        soul.add("term" => @blog.title, "id" => @blog.id, "data" => {"url" => edit_dashboard_blog_path(@blog.slug), "subtitle" => @blog.title})
        
        format.html { redirect_to dashboard_blog_path(@blog), notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @blog = current_account.blogs.find_by_slug(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        
        soul = Soulmate::Loader.new("blog #{current_account.id}")
        soul.add("term" => @blog.title, "id" => @blog.id, "data" => {"url" => edit_dashboard_blog_path(@blog.slug), "subtitle" => @blog.title})
        
        
        format.html { redirect_to dashboard_blog_path(@blog), notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @blog = current_account.blogs.find_by_slug(params[:id])
    
    soul = Soulmate::Loader.new("blog_#{current_account.id}")
    soul.remove("id" => @blog.id)
    
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to dashboard_blogs_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/dashboard/cards_controller.rb
class Dashboard::CardsController < Dashboard::DashboardController
  
  before_filter :setup_menu

  def setup_menu
    gon.menu_active_accordian = 3
    gon.menu_active_link = 'cards'
  end
  
  
  def index
    @cards = current_account.cards.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
    end
  end


  def show
    @card = current_account.cards.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end

  def new
    @card = current_account.cards.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
    end
  end


  def edit
    @card = current_account.cards.find(params[:id])
  end


  def create

    @card = current_account.cards.new(params[:card])

    respond_to do |format|
      if @card.save
        
        if @card.default
      
          @cards = current_account.cards.all
      
          @cards.each do |card|
            if card.default
              card.default = false
              card.save
            end
          end
          @card.default = true
          @card.save
          
        end
        
        
             
        format.html { redirect_to dashboard_cards_path, notice: 'Card was successfully created.' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @card = current_account.cards.find(params[:id])
    
    # if @card.number != params[:card][:number]
    # 
    #   credit_card = ActiveMerchant::Billing::CreditCard.new(params[:card])
    #   
    #   if !credit_card.valid?
    #     render action: "edit"
    #   end
    # end

    if @card.update_attributes(params[:card])
        
        if @card.default == true
      
          @cards = current_account.cards.all
      
          @cards.each do |card|
            if card.id != @card.id
              if card.default
                card.default = false
                card.save
              end
            end
          end

        end
        
        redirect_to dashboard_cards_path, notice: 'Card was successfully updated.'
        

    else
      render action: "edit"
    end

  end


  def destroy
    @card = current_account.cards.find(params[:id])
    if !@card.default
      @card.destroy
    end

    respond_to do |format|
      format.html { redirect_to dashboard_cards_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/dashboard/comments_controller.rb
class Dashboard::CommentsController < Dashboard::DashboardController  
  
  before_filter :load_commentable
  
  def index
    @comments = @commentable.comments
  end

  def new
    @comment = @commentable.comments.new
  end

  def create

    @comment = @commentable.comments.new(params[:comment])
    if @comment.save
      redirect_to dashboard_blog_path(@commentable), notice: "Comment created."
    else
      render :new
    end
  end

private

  def load_commentable
    @commentable = current_account.blogs.find_by_slug(params[:blog_id])

  end

  # alternative option:
  # def load_commentable
  #   klass = [Blog].detect { |c| params["#{c.name.underscore}_id"] }
  #   @commentable = klass.find(params["#{klass.name.underscore}_id"])
  # end
end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < ApplicationController
  layout "dashboard"

  before_filter :authenticate_account!
  # before_filter :set_timezone
  before_filter :setup_system
  before_filter :setup_menu
  
  respond_to :html, :json, :js
  
  add_breadcrumb "Dashboard", :dashboard_path
  
  def setup_menu
    
    gon.menu_active_accordian = 0
    gon.menu_active_link = 'dashboard'
  end

  
  def setup_system
    gon.search_fields = ['user', 'listings 4fd6395e9a6f23070e00003b', "page #{current_account.id}", "blog #{current_account.id}"]
  end
  
  def index
    gon.menu_active_link = 'dashboard'
    # @listings = Listing.all.cache
    
    @listings = Listing.limit(5).cache
    
    
    
  end
  
  def install_facebook(page_id)

    # Id of the RESB Application
    app_id = '208065319210030'
    
    @page_token = @facebook.get_page_access_token(page_id.to_s)
    
    @page_graph = Koala::Facebook::GraphAPI.new(@page_token['access_token'])
    
    @page_application = @page_graph.get_connections(page_id, 'tabs/'+app_id)
    
    # Check to see if the application is not installed
  
    @install_application_response = @page_graph.put_connections(page_id, 'tabs', :app_id => app_id)


    
  end
  
  
  def uninstall_facebook(page_id)

    # Id of the RESB Application
    app_id = '208065319210030'
    
    @page_token = @facebook.get_page_access_token(page_id.to_s)
    
    @page_graph = Koala::Facebook::GraphAPI.new(@page_token['access_token'])
    
    @page_application = @page_graph.get_connections(page_id, 'tabs/'+app_id.to_s).first
    # raise @page_application['id']
    # Check to see if the application is not installed
    if @page_application
      @uninstall_application_response = @page_graph.delete_object(@page_application['id'].to_s)
    end
    # raise @uninstall_application_response.to_yaml

    
  end
  
  def settings
    
    gon.menu_active_accordian = 3
    gon.menu_active_link = 'settings'
    add_breadcrumb "Settings", dashboard_settings_path
    
    if params[:account]
      
      
      # @account.realtor.find(current_account)
      # raise current_account.to_json
      
      # current_facebook_page_id = current_account.facebook_page_id if @facebook
      
      
      if current_account.update_attributes(params[:account])
        # 
        # if !params[:account][:internal_agent_nrds_id].nil?
        #   agent = Agent.find_by(internal_agent_nrds_id: params[:account][:internal_agent_nrds_id])
        # 
        #   current_account.agent_id = agent.id.to_s
        #   # current_account.agent_attributes = {id: agent.id.to_s}
        #   current_account.save
        #   raise agent.to_json
        # end
          
          
          # if current_facebook_page_id != params[:account][:facebook_page_id] && @facebook
          #             install_facebook(params[:account][:facebook_page_id])
          #             uninstall_facebook(current_facebook_page_id)
          #           end
          
          
        # raise @account.to_json
          
        redirect_to dashboard_settings_path, notice: 'Settings was successfully updated.'
      else
        render action: "settings"
      end

    else
      # @facebook_pages = @facebook.get_connections("me", "accounts") if @facebook
    end
  end
  
  def support

  end

  private
  
    # Set the users current timezone
    def set_timezone
      Time.zone = current_account.time_zone if current_account.time_zone
    end

end

app/controllers/dashboard/facebook_posts_controller.rb
class Dashboard::FacebookPostsController < Dashboard::DashboardController

  before_filter :setup_menu
  # before_filter :setup_fb_pages

  def setup_menu
    gon.menu_active_accordian = 0
    gon.menu_active_link = 'facebook_posts'
  end
  
  def setup_fb_pages
    @facebook_pages = current_account.facebook.get_connections("me", "accounts") if current_account.facebook
    
    # raise @facebook_pages.to_yaml
    
    if @facebook_pages
      @facebook_pages.each do |fb_page|
    
        if fb_page['category'] != 'Application'
          page_graph = Koala::Facebook::GraphAPI.new(fb_page['access_token'])
          page = page_graph.get_object("me")
          # raise page.to_yaml

          facebook_page = current_account.facebook_pages.new
      
          facebook_page.realtor_id = current_account.id.to_s
          facebook_page.name = fb_page['name']
          facebook_page.access_token = fb_page['access_token']
          facebook_page.category = fb_page['category']
          facebook_page.fb_page_id = fb_page['id']
          facebook_page.perms = fb_page['perms'] if fb_page['perms']
        
          facebook_page.picture = page['picture']
          facebook_page.link = page['link']
          facebook_page.likes = page['likes']
          facebook_page.is_published = page['is_published']
          facebook_page.website = page['website']
          facebook_page.has_added_app = page['has_added_app']
          facebook_page.username = page['username']
          facebook_page.founded = page['founded']
          facebook_page.description = page['description']
          facebook_page.about = page['about']
          facebook_page.release_date = page['release_date']
          facebook_page.can_post = page['can_post']
          facebook_page.talking_about_count = page['talking_about_count']
      
          facebook_page.save
        end
      
      end
    end

  end


  def index
    @facebook_posts = current_account.facebook_posts.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @facebook_posts }
    end
  end


  def show
    @facebook_post = current_account.facebook_posts.find(params[:id])

    respond_to do |format|
      format.html { render "edit" }
      format.json { render json: @facebook_post }
    end
  end

  def new
    @facebook_post = current_account.facebook_posts.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @facebook_post }
    end
  end


  def edit
    @facebook_post = current_account.facebook_posts.find(params[:id])
  end


  def create
    @facebook_post = current_account.facebook_posts.new(params[:facebook_post])

    # raise @facebook_post.to_yaml

    respond_to do |format|
      if @facebook_post.save
        
        # @facebook_page = current_account.facebook_pages.find(@facebook_post.facebook_page_id)
        
        # raise @facebook_page.to_yaml
        
        # @page_graph = Koala::Facebook::GraphAPI.new(@facebook_page.access_token)
        # @page_application = @page_graph.get_connections(@facebook_page.fb_page_id, 'accounts', @facebook_page.access_token)
        # raise @page_application.to_yaml
        # 
        # @page_graph.put_connections(@facebook_page.fb_page_id, 'feed', :message => 'This is posted as the page')
        # post = @page_graph.put_connections(@facebook_page.fb_page_id, 'feed', :message => 'Testing some new features!')
        #         raise post.to_yaml
        
        
        format.html { redirect_to dashboard_facebook_posts_path, notice: 'Facebook Post was successfully created.' }
        format.json { render json: @facebook_post, status: :created, location: @facebook_post }
      else
        format.html { render action: "new" }
        format.json { render json: @facebook_post.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @facebook_post = current_account.facebook_posts.find(params[:id])

    respond_to do |format|
      if @facebook_post.update_attributes(params[:facebook_post])
        
        format.html { redirect_to dashboard_facebook_posts_path, notice: 'Facebook Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @facebook_post.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @facebook_post = current_account.facebook_posts.find(params[:id])
    @facebook_post.destroy

    redirect_to dashboard_facebook_posts_path
  end
end

app/views/dashboard/pages/_children.html.haml
%ol
  - page.children.each do |child|
    %li{:id => "page_#{child.id}"}
      %div
        %span.actions.pull-right
          = link_to edit_dashboard_page_path(child) do
            %i.icon-edit.action_links
          = link_to dashboard_page_path(child), :confirm => t("dashboard.pages.buttons.delete.confirm"), :method => :delete do
            %i.icon-trash.action_links
        %i.icon-move.action_links
        = child.title
        
        - if child.page_type == 2
          %span.badge.badge-success
            Facebook Page
        - elsif child.page_type == 3
          %span.badge.badge-success
            Home Page
        - elsif child.page_type == 4
          %span.badge.badge-success
            Contact Page
        - elsif child.page_type == 5
          %span.badge.badge-success
            Listings Page
        - elsif child.page_type == 6
          %span.badge.badge-success
            Blog Page
        - else
        
      = render 'children', :page => child unless child.leaf?

app/views/dashboard/pages/_form.html.haml
= semantic_form_for [:dashboard, @page] do |f|
  = f.inputs do
    = f.input :title
    = f.input :content, :as => :ckeditor, :label => false, :input_html => { :toolbar => 'Easy' }
    = f.input :tags
    
    = f.inputs :name => 'Optional Settings' do
      = f.input :published, :as => :boolean
      = f.input :parent, :collection => @build_tree_select, :prompt => "New parent page"
      = f.input :page_type, :collection => page_type, :prompt => false, :include_blank => false
      
      
      = f.input :seo_meta_title, :label => 'SEO Title'
      = f.input :seo_meta_keys, :label => 'SEO Keywords'
      = f.input :seo_meta_desc, :label => 'SEO Description'

  = f.actions do
    = f.action :submit, :label => t(".buttons.save.content").html_safe, :as => :button, :button_html => { :class => t(".buttons.save.css") }

app/views/dashboard/pages/edit.html.haml
.page
  .header
    .links
      = link_to new_dashboard_page_path, :class => t("dashboard.pages.buttons.add.css"), :title => t("dashboard.pages.buttons.add.title") do
        = t("dashboard.pages.buttons.add.content").html_safe
      = link_to dashboard_pages_path(@page), :class => t("dashboard.pages.buttons.delete.css"), :title => t("dashboard.pages.buttons.delete.title"), :confirm => t("dashboard.pages.buttons.delete.confirm"), :method => :delete do
        = t("dashboard.pages.buttons.delete.content").html_safe
      = link_to dashboard_pages_path, :class => t("dashboard.pages.buttons.index.css"), :title => t("dashboard.pages.buttons.index.title") do
        = t("dashboard.pages.buttons.index.content").html_safe
    .title
      = t(".title").html_safe
      
  .content
    = render 'form'
    
  .back
    = link_to  dashboard_pages_path do
      %i.icon-arrow-left
      Go Back

app/views/dashboard/pages/index.html.haml
.page
  .header
    .links
      = link_to new_dashboard_page_path, :class => t("dashboard.pages.buttons.add.css"), :title => t("dashboard.pages.buttons.add.title") do
        = t("dashboard.pages.buttons.add.content").html_safe
    .title
      = t(".title").html_safe
  .content
    .well
      
      %h4
        %i.icon-moved
        Drag and Drop Menu Builder
      %p
        By dragging and dropping pages you can build custom multi-tiered navigation menus for both your Website and Facebook. To create Sub Navigation Links under any link Drag the link to the right.
  
  
#output

%ol.sortable
  - @pages.roots.each do |page|
    %li{:id => "page_#{page.id}"}
      %div
        %span.actions.pull-right
          = link_to edit_dashboard_page_path(page) do
            %i.icon-edit.action_links
          = link_to dashboard_page_path(page), :confirm => t("dashboard.pages.buttons.delete.confirm"), :method => :delete do
            %i.icon-trash.action_links
        %i.icon-move.action_links
        = page.title
        
        - if page.page_type == 2
          %span.badge.badge-success
            Facebook Page
        - elsif page.page_type == 3
          %span.badge.badge-success
            Home Page
        - elsif page.page_type == 4
          %span.badge.badge-success
            Contact Page
        - elsif page.page_type == 5
          %span.badge.badge-success
            Listings Page
        - elsif page.page_type == 6
          %span.badge.badge-success
            Blog Page
        - else
          
        
      = render 'children', :page => page unless page.leaf?

app/views/dashboard/pages/new.html.haml
.page
  .header
    .links
      = link_to dashboard_pages_path, :class => t("dashboard.pages.buttons.index.css"), :title => t("dashboard.pages.buttons.index.title") do
        = t("dashboard.pages.buttons.index.content").html_safe
    .title
      = t(".title").html_safe
      
  .content
    = render 'form'
    
  .back
    = link_to  dashboard_pages_path do
      %i.icon-arrow-left
      Go Back