config/routes.rb
Resocialbuilder::Application.routes.draw do
  
  

  constraints(:subdomain => 'soulmate') do
    mount Soulmate::Server, :at => '/'
  end
  
  constraints(:subdomain => 'dev') do
    mount Resque::Server, :at => '/resque'
    scope :module => "dev" do
      get '/sprites/:id' => 'dev#sprites'
      get '/sprites' => 'dev#sprites'
      get '/schema' => 'dev#schema'
      root to: "dev#index"
    end
  end
  
  match '/dashboard', to: 'dashboard::dashboard#index', as: 'dashboard'
  match '/login', to: 'accounts#login'
  match '/logout', to: 'sessions#logout'

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure', to: 'home::register#new', as: 'register'
  
  
  match 'listings/nnrmls', to: 'listings#nnrmls', as: 'nnrmls'
  match 'listings/stgeorge', to: 'listings#stgeorge', as: 'stgeorge'
  match 'listings/mls', to: 'listings#mls', as: 'mls'
  
  mount Ckeditor::Engine => "/ckeditor"
  
  namespace :dashboard do
    
    
    
    match '/', to: 'dashboard#index', as: 'dashboard'
    match '/mls', to: 'dashboard#mls', as: 'mls'
    match '/menu', to: 'dashboard#menu', as: 'menu'
    match '/support', to: 'dashboard#support', as: 'support'
    match '/settings', to: 'dashboard#settings', as: 'settings'
    post '/savesort' => 'pages#savesort'
    
    
    
    resources :blogs do
      resources :comments
    end
    
    get 'blogs/:id/manage_comments', to: 'blogs#manage_comments', as: 'manage_comments'
    
    resources :accounts
    resources :comments
    resources :pages
    resources :links
    resources :widgets
    resources :realtors
    resources :listings
    resources :transactions
    resources :cards
    resources :facebook_posts

    
  end
  
  
  
  constraints(Subdomain) do
    
    namespace :api do
      namespace :v1, :defaults => { :format => 'json' } do
        resources :blogs
        resources :pages
        resources :accounts
        resources :listings
      end
    end
  
    post '/emails', to: 'profile::profile#emails', as: 'emails', :via => :post


    get '/listings', to: 'profile::profile#listings', as: 'listings', :via => :get
    match '/listing/:mls_list_id', to: 'profile::profile#listing', as: 'listing', :via => :get
    
    
    
    get '/blogs', to: 'profile::profile#blogs', as: 'blogs', :via => :get
    match '/blog/:id', to: 'profile::profile#blog', as: 'blog', :via => :get
    
    match '/search', to: 'profile::profile#search', as: 'searches', :via => :get
    resources :search

    match '/:id', to: 'profile::profile#page', as: 'page', :via => :get

    
    root to: 'profile::profile#index'
  end
  

  resources :accounts
  resources :realtors
  resources :listings
  
  root :to => 'home::home#index'
  
end

app/controllers/home/home_controller.rb
class Home::HomeController < ApplicationController
  layout "home"

  respond_to :html

  def index
    
    

  end

  
  def facebook
    
    
    # raise @graph.get_object("me").to_yaml
    
    # post_to_wall = @graph.put_wall_post("T your gay")
    #     raise post_to_wall.to_yaml
    #     
    #     search = @graph.search("time+supply supply", {:type => "post"})
    #     raise search.to_yaml
    likes = @graph.get_connections("me", "likes")
    raise likes.to_yaml
    profile = @graph.get_object("me")
    friends = @graph.get_connections("me", "friends")
    pages = @graph.get_connections("me", "accounts")
    # raise pages.to_yaml
    
    # page_token = @graph.get_page_access_token(142429665816884)
    # => access_token
    # (if you don't get access_token, you're missing the manage_pages permission)
    @page_graph = Koala::Facebook::API.new('AAAC9OZCtxDC4BAI3Wm40Snz8lxpxQ7ZATwZAIatwUeE72sxweKX1RvU2jDtRV9Utiv1luwGKOIOFzfsaHlb7SuwsGclT7hrnEeaqGYKJvvwsiEPK8bF')
    
    raise @page_graph.to_yaml
    
    
    raise friends.to_yaml
    raise profile.to_yaml
    
  end
  
  
end

app/views/home/home/index.html.haml
.page.home

  .left
  
    #mediaplayer JW Player goes here
    :javascript
      jwplayer("mediaplayer").setup({
        skin: "jwplayer/glow.zip",
        stretching: "fill",
        flashplayer: "jwplayer/player.swf",
        file: "http://content.bitsontherun.com/videos/bkaovAYt-364766.mp4",
        image: "http://s0-www.ltvimg.com/v3_6_4/images/jw-player/bkaovAYt-480.jpg"
      });

  .right
    .padding_10
      %h1 Why Sign Up with RE Social Builder?
      
      %ul
        %li Deliver your MLS Listings directly on Facebook!
        %li Every account gets a personalized website.
        %li Allow your customers to search the entire MLS in your area.
        %li Upload company logo, and personal image to website and Facebook.
        %li Personalized subdomain URL for ease of access to website.
        %li Personal or Business blog with absolutely no restrictions!
        %li 100% Real Time website traffic analytics.
      = link_to 'Create your account', new_account_path, :class => 'button green'